services:
  - type: web
    name: salone4d-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: CHANNEL_ID
        value: "@mexes30salone"
      - key: RUN_MODE
        value: "all"
